PRM sample
microsoft/Windows-driver-samples pull request #1091
Opened 2024-01-26 21:32 UTC by yinghany

Add a new WDF driver sample to demonstrate the usage of the PRM direct-call interface.

2024-01-27 07:07 UTC, JakobL-MSFT requested changes
Sent email with details!

2024-01-30 00:05 UTC, NeoAdonis commented
* Unless you expect to have more PRM samples, you should move the contents of prm/samples to simply prm to simplify folder structure.
* If possible, please add support for ARM64.

2024-01-30 00:06 UTC, NeoAdonis requested changes

2024-01-30 00:06 UTC, NeoAdonis commented on prm/samples/PrmFunc/prmfuncsample.vcxproj
> +    <PlatformToolset>WindowsKernelModeDriver11.0</PlatformToolset>
This platform toolset does not exist.

2024-01-30 00:06 UTC, NeoAdonis commented on prm/samples/PrmFunc/prmfuncsample.vcxproj
> +    <PlatformToolset>WindowsKernelModeDriver11.0</PlatformToolset>
This platform toolset does not exist.

2024-01-31 00:41 UTC, NeoAdonis approved these changes

2024-01-31 00:46 UTC, JakobL-MSFT commented
@NeoAdonis : Sample still does not build!!  See build failure.

2024-01-31 19:47 UTC, yinghany commented
> @NeoAdonis : Sample still does not build!! See build failure.

@JakobL-MSFT What is the WDK version that you are building with? This is a new sample reliant on Ge WDK headers (prminterface.h).

2024-01-31 20:36 UTC, JakobL-MSFT commented
> @JakobL-MSFT What is the WDK version that you are building with? This is a new sample reliant on Ge WDK headers (prminterface.h).

Now I understand!!!  

First. You need to target our "develop" branch.  Not "main".

Second.  The samples in the develop branch needs to build with (1) "in market" EWDK and (2) also GE EWDK.  Exceptions can happen (as in your case) and we add them to .\exclusions.csv file in relevant branch.  The entry would look as follows:
---
prm\prmsample,*,,22621,Only NI: Not supported on NI.
---

(Please note the .\exclusion.csv file differs between main and develop branch.  You need to edit based on the develop branch version)

I can make the edit above (or you can add it - please keep the entries sorted)

Cheers.

Jakob

2024-01-31 22:43 UTC, closed without merging