Ndis mux inf violations
microsoft/Windows-driver-samples pull request #973
Opened 2023-04-11 23:25 UTC by kahashimoto-ms

Fix INF violations. Fix Prefast warnings. Fix encoding on INF file. Add the correct build number needed to install using DIRID 13.

2023-04-13 16:47 UTC, jasonknichel requested changes

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/notifyob/adapter.cpp
> +                                lResult = E_INVALIDARG;
lResult is used above to capture returns fro Reg* APIs which return Win32 errors, but you are assigning a HRESULT into it here.  You shouldn't mix HRESULT and Win32 error like this.  Should this be lResult = ERROR_INVALID_PARAMETER; or lResult = ERROR_INVALID_DATA; instead?

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/notifyob/adapter.cpp
> +        return ERROR_BUFFER_OVERFLOW;
This function returns an HRESULT but ERROR_BUFFER_OVERFLOW is a Win32 error.  Should this be HRESULT_FROM_WIN32(ERROR_BUFFER_OVERFLOW); instead?

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/notifyob/common.cpp
> +        {
This and other added code doesn't match the existing curly brace style of this file

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/notifyob/common.cpp
> +                    return ERROR_BUFFER_OVERFLOW;
This function returns an HRESULT but ERROR_BUFFER_OVERFLOW is a Win32 error. Should this be HRESULT_FROM_WIN32(ERROR_BUFFER_OVERFLOW); instead?

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/notifyob/common.cpp
> +            return ERROR_BUFFER_OVERFLOW;
Also, is this early return leaking pencc since ReleaseObj( pencc ); is being skipped?

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/notifyob/common.cpp
> +                    return ERROR_BUFFER_OVERFLOW;
Also, is this early return leaking pencc since ReleaseObj( pencc ); is being skipped?

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/notifyob/notify.cpp
> +                {
not matching existing curly brace style

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/notifyob/notify.cpp
> +                    lResult = E_INVALIDARG;
You are assigning an HRESULT to lResult which this function uses for Win32 errors.

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/notifyob/virtual.cpp
> +            {
not matching the brace style of existing code

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/notifyob/virtual.cpp
> +                return ERROR_BUFFER_OVERFLOW;
you are returning a win32 error here, but this function should return an HRESULT.

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/notifyob/virtual.cpp
> +                    return ERROR_BUFFER_OVERFLOW;
you are returning a win32 error here, but this function should return an HRESULT.

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/notifyob/virtual.cpp
> +                    return ERROR_BUFFER_OVERFLOW;
this early return is leaking szAdapterGuidKey

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/notifyob/virtual.cpp
> +                return ERROR_BUFFER_OVERFLOW;
you are returning a win32 error here, but this function should return an HRESULT.

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/notifyob/virtual.cpp
> +                    return ERROR_BUFFER_OVERFLOW;
you are returning a win32 error here, but this function should return an HRESULT.

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/notifyob/virtual.cpp
> +                    return ERROR_BUFFER_OVERFLOW;
this early return is leaking szAdapterGuidKey

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/driver/60/mux_mp.inf
This is in class Net, so do the comments about the Network Installation UI and the build number filtering still apply or was that just for the NetTrans and/or NetService/NetClient ones you modified earlier?

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/driver/60/mux_mp.inf
mux_mp.inf adds a service that uses mux.sys, but it doesn't payload mux.sys.  You need a [SourceDisksNames], [SourceDisksFiles], [DestinationDirs], and CopyFiles for it.

2023-04-13 16:47 UTC, jasonknichel commented on network/ndis/mux/driver/60/muxp.inf
You have some "CHECK THIS" comments still in there:

MUXP_NC.CopyFiles.DLL  = 11 ;CHECK THIS
MUXP_NC.CopyFiles.Sys  = 12    ;CHECK THIS

2023-04-20 04:21 UTC, kahashimoto-ms commented on network/ndis/mux/driver/60/mux_mp.inf
This is an intermediate driver which require two INF files. One of the INF files (muxp.inf) defines the installation for the protocol lower edge. The other INF file (mux_mp.inf) defines the installation for the virtual miniport upper edge. The protocol INF, (muxp.inf) is the primary INF file. After the protocol is installed the miniport upper edge is installed. The protocol INF installs a DLL, which can only be properly installed with OS build number 25341 or latter. The miniport INF does not install a DLL so the build number of 25341 is not necessary. However, I thought it would make more sense if the two INF files used the same DIRID during installation. If the build number was set to a lower number in the miniport driver INF, you could end up in a situation where the protocol was installed using DIRID 12 and the miniport was installed using DIRID 13. I am not sure that this is a bad thing, I just thought it could cause some confusion. That is why the build number of 25341 is used in both INF files.

2023-04-20 04:22 UTC, kahashimoto-ms commented on network/ndis/mux/driver/60/mux_mp.inf
Should I change the comment to explain that?

2023-04-20 21:56 UTC, kahashimoto-ms commented on network/ndis/mux/driver/60/mux_mp.inf
I edited the comment to explain why the build number is 25341 in this INF file as well.

2023-04-21 18:04 UTC, jasonknichel requested changes

2023-04-21 21:12 UTC, jasonknichel approved these changes

2023-04-21 21:16 UTC, merged